name: Build and Deploy
on:
  push:
    branches:
      - master
      - deploy-to-pages #todo: remove before merging
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.18.4'

      - name: Install and Build 
        run: |
          npm ci
          npm run build
 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages 
          folder: build
                  
    